Fix COM thread model issue
The following issue happens when trying to extend volumes using VDS:

OSError: [WinError -2147417850] Cannot change thread mode after it
is set

sys.coinit_flags needs to be set before importing pythoncom.

Change-Id: I83877219b9589d9c174fd3a245b644350ea6310a
Closes-Bug: #1787659